// Placeable structures. `tier` is the base tier required.
// Power: generators add `power`, consumers spend `powerUse`.
// Turrets shoot only while they have power (or if powerUse is 0).

export const BUILDINGS = {
  hearth: {
    name: "Pyre Hearth",
    tier: 0,
    cat: "basic",
    style: "pyre",
    cost: {},
    hp: 1200,
    size: [2, 2],
    blocksPlayer: true,
    blocksZombies: true,
    blocksCrawlers: true,
    unique: true,
    hidden: true,
    core: true,
  },
  wood_wall: {
    name: "Wooden Wall",
    tier: 0,
    cat: "basic",
    style: "wall",
    cost: { wood: 20 },
    hp: 500,
    size: [1, 1],
    blocksPlayer: true,
    blocksZombies: true,
    blocksCrawlers: true,
  },
  wood_floor: {
    name: "Wooden Floor",
    tier: 0,
    cat: "basic",
    style: "floor",
    cost: { wood: 8 },
    hp: 180,
    size: [1, 1],
    blocksPlayer: false,
    blocksZombies: false,
    blocksCrawlers: false,
  },
  wood_gate: {
    name: "Wooden Gate",
    tier: 0,
    cat: "basic",
    style: "gate",
    cost: { wood: 28 },
    hp: 420,
    size: [1, 1],
    blocksPlayer: false,
    blocksZombies: true,
    blocksCrawlers: true,
    gate: true,
  },
  barricade: {
    name: "Barricade",
    tier: 0,
    cat: "basic",
    style: "barricade",
    cost: { wood: 14 },
    hp: 260,
    size: [1, 1],
    blocksPlayer: true,
    blocksZombies: true,
    blocksCrawlers: false,
  },
  storage_small: {
    name: "Small Storage",
    tier: 0,
    cat: "basic",
    style: "storage",
    cost: { wood: 30 },
    hp: 360,
    size: [1, 1],
    blocksPlayer: true,
    blocksZombies: true,
    blocksCrawlers: true,
    storage: true,
  },
  campfire: {
    name: "Campfire",
    tier: 0,
    cat: "basic",
    style: "campfire",
    cost: { wood: 12 },
    hp: 140,
    size: [1, 1],
    blocksPlayer: false,
    blocksZombies: false,
    blocksCrawlers: false,
    heal: 0.8,
    healRadius: 6,
  },
  watchtower: {
    name: "Watchtower",
    tier: 0,
    cat: "basic",
    style: "tower",
    cost: { wood: 45, stone: 12 },
    hp: 480,
    size: [1, 1],
    blocksPlayer: true,
    blocksZombies: true,
    blocksCrawlers: true,
    turret: { range: 18, damage: 9, rate: 1.05, kind: "bullet" },
    upgradeable: true,
  },
  stone_wall: {
    name: "Stone Wall",
    tier: 1,
    cat: "fort",
    style: "wall",
    cost: { stone: 40, wood: 10 },
    hp: 1500,
    size: [1, 1],
    blocksPlayer: true,
    blocksZombies: true,
    blocksCrawlers: true,
  },
  stone_gate: {
    name: "Stone Gate",
    tier: 1,
    cat: "fort",
    style: "gate",
    cost: { stone: 48, wood: 16 },
    hp: 1300,
    size: [1, 1],
    blocksPlayer: false,
    blocksZombies: true,
    blocksCrawlers: true,
    gate: true,
  },
  stone_tower: {
    name: "Stone Tower",
    tier: 1,
    cat: "fort",
    style: "tower",
    cost: { stone: 70, wood: 24 },
    hp: 1700,
    size: [1, 1],
    blocksPlayer: true,
    blocksZombies: true,
    blocksCrawlers: true,
    turret: { range: 26, damage: 20, rate: 0.65, kind: "bullet" },
    upgradeable: true,
  },
  workshop: {
    name: "Workshop",
    tier: 1,
    cat: "fort",
    style: "workshop",
    cost: { wood: 55, stone: 35, gold: 120 },
    hp: 900,
    size: [2, 2],
    blocksPlayer: true,
    blocksZombies: true,
    blocksCrawlers: true,
    unique: true,
    workshop: true,
  },
  storage_large: {
    name: "Resource Storage",
    tier: 1,
    cat: "fort",
    style: "storage",
    cost: { wood: 40, stone: 45 },
    hp: 980,
    size: [2, 1],
    blocksPlayer: true,
    blocksZombies: true,
    blocksCrawlers: true,
    storage: true,
  },
  lumber_yard: {
    name: "Lumber Rack",
    tier: 1,
    cat: "fort",
    style: "gen",
    cost: { wood: 70, gold: 90 },
    hp: 520,
    size: [2, 1],
    blocksPlayer: true,
    blocksZombies: true,
    blocksCrawlers: true,
    generates: { wood: 1 },
    interval: 8,
  },
  barracks: {
    name: "Barracks",
    tier: 2,
    cat: "fort",
    style: "hall",
    cost: { wood: 40, stone: 70, gold: 220 },
    hp: 1100,
    size: [2, 2],
    blocksPlayer: true,
    blocksZombies: true,
    blocksCrawlers: true,
    unique: true,
    barracks: true,
  },
  armory: {
    name: "Armory",
    tier: 2,
    cat: "fort",
    style: "hall",
    cost: { stone: 55, metal: 18, gold: 280 },
    hp: 1200,
    size: [2, 2],
    blocksPlayer: true,
    blocksZombies: true,
    blocksCrawlers: true,
    unique: true,
    armory: true,
  },
  mg_turret: {
    name: "Machine Gun Turret",
    tier: 2,
    cat: "fort",
    style: "turret",
    cost: { metal: 28, stone: 24, gold: 450 },
    hp: 980,
    size: [1, 1],
    blocksPlayer: true,
    blocksZombies: true,
    blocksCrawlers: true,
    powerUse: 1,
    turret: { range: 22, damage: 7, rate: 8, kind: "bullet" },
    upgradeable: true,
  },
  quarry_hopper: {
    name: "Quarry Hopper",
    tier: 2,
    cat: "fort",
    style: "gen",
    cost: { wood: 30, stone: 60, gold: 160 },
    hp: 740,
    size: [2, 1],
    blocksPlayer: true,
    blocksZombies: true,
    blocksCrawlers: true,
    generates: { stone: 1 },
    interval: 10,
  },
  metal_wall: {
    name: "Metal Wall",
    tier: 3,
    cat: "military",
    style: "wall",
    cost: { metal: 50, stone: 25 },
    hp: 4000,
    size: [1, 1],
    blocksPlayer: true,
    blocksZombies: true,
    blocksCrawlers: true,
  },
  metal_gate: {
    name: "Metal Gate",
    tier: 3,
    cat: "military",
    style: "gate",
    cost: { metal: 45, stone: 20, gold: 80 },
    hp: 3400,
    size: [1, 1],
    blocksPlayer: false,
    blocksZombies: true,
    blocksCrawlers: true,
    gate: true,
  },
  sniper_tower: {
    name: "Sniper Tower",
    tier: 3,
    cat: "military",
    style: "tower",
    cost: { metal: 40, stone: 36, gold: 900 },
    hp: 1500,
    size: [1, 1],
    blocksPlayer: true,
    blocksZombies: true,
    blocksCrawlers: true,
    powerUse: 1,
    turret: { range: 48, damage: 58, rate: 0.42, kind: "sniper" },
    upgradeable: true,
  },
  generator: {
    name: "Generator",
    tier: 3,
    cat: "military",
    style: "generator",
    cost: { metal: 45, gold: 700 },
    hp: 980,
    size: [2, 1],
    blocksPlayer: true,
    blocksZombies: true,
    blocksCrawlers: true,
    power: 4,
  },
  medical: {
    name: "Medical Station",
    tier: 3,
    cat: "military",
    style: "medical",
    cost: { metal: 22, wood: 24, gold: 550 },
    hp: 760,
    size: [1, 1],
    blocksPlayer: true,
    blocksZombies: true,
    blocksCrawlers: true,
    powerUse: 1,
    heal: 2.6,
    healRadius: 11,
  },
  command: {
    name: "Command Center",
    tier: 3,
    cat: "military",
    style: "command",
    cost: { metal: 55, stone: 40, gold: 1400 },
    hp: 1600,
    size: [2, 2],
    blocksPlayer: true,
    blocksZombies: true,
    blocksCrawlers: true,
    unique: true,
    command: true,
    powerUse: 1,
  },
  scrap_press: {
    name: "Scrap Press",
    tier: 3,
    cat: "military",
    style: "gen",
    cost: { metal: 36, gold: 480 },
    hp: 860,
    size: [2, 1],
    blocksPlayer: true,
    blocksZombies: true,
    blocksCrawlers: true,
    generates: { metal: 1 },
    interval: 14,
  },
  steel_gate: {
    name: "Steel Gate",
    tier: 4,
    cat: "end",
    style: "gate",
    cost: { metal: 100, gold: 50 },
    hp: 7200,
    size: [1, 1],
    blocksPlayer: false,
    blocksZombies: true,
    blocksCrawlers: true,
    gate: true,
  },
  electric_fence: {
    name: "Electric Fence",
    tier: 4,
    cat: "end",
    style: "fence",
    cost: { metal: 32, gold: 240 },
    hp: 1900,
    size: [1, 1],
    blocksPlayer: true,
    blocksZombies: true,
    blocksCrawlers: true,
    powerUse: 1,
    shock: 24,
  },
  rocket_turret: {
    name: "Rocket Turret",
    tier: 4,
    cat: "end",
    style: "turret",
    cost: { metal: 80, gold: 2200 },
    hp: 1400,
    size: [1, 1],
    blocksPlayer: true,
    blocksZombies: true,
    blocksCrawlers: true,
    powerUse: 2,
    turret: { range: 34, damage: 150, rate: 0.33, kind: "rocket", splash: 3.6 },
    upgradeable: true,
  },
  auto_turret: {
    name: "Automated Turret",
    tier: 4,
    cat: "end",
    style: "turret",
    cost: { metal: 60, gold: 1800 },
    hp: 1300,
    size: [1, 1],
    blocksPlayer: true,
    blocksZombies: true,
    blocksCrawlers: true,
    powerUse: 2,
    turret: { range: 24, damage: 15, rate: 6.2, kind: "bullet" },
    upgradeable: true,
  },
  missile_defense: {
    name: "Missile Defense",
    tier: 4,
    cat: "end",
    style: "missile",
    cost: { metal: 100, gold: 3800 },
    hp: 1800,
    size: [2, 2],
    blocksPlayer: true,
    blocksZombies: true,
    blocksCrawlers: true,
    powerUse: 4,
    unique: true,
    turret: { range: 52, damage: 230, rate: 0.22, kind: "rocket", splash: 4.6, priority: "big" },
  },
  fortress_wall: {
    name: "Reinforced Fortress Wall",
    tier: 5,
    cat: "end",
    style: "wall",
    cost: { metal: 80, stone: 40, gold: 120 },
    hp: 10000,
    size: [1, 1],
    blocksPlayer: true,
    blocksZombies: true,
    blocksCrawlers: true,
  },
  laser_turret: {
    name: "Laser Defense",
    tier: 5,
    cat: "end",
    style: "laser",
    cost: { metal: 90, gold: 6500 },
    hp: 1600,
    size: [1, 1],
    blocksPlayer: true,
    blocksZombies: true,
    blocksCrawlers: true,
    powerUse: 3,
    turret: { range: 30, damage: 46, rate: 4, kind: "laser" },
    upgradeable: true,
  },
  bunker: {
    name: "Underground Bunker",
    tier: 5,
    cat: "end",
    style: "bunker",
    cost: { metal: 110, stone: 90, gold: 4500 },
    hp: 3200,
    size: [2, 2],
    blocksPlayer: true,
    blocksZombies: true,
    blocksCrawlers: true,
    unique: true,
    bunker: true,
  },
  lab: {
    name: "Research Laboratory",
    tier: 5,
    cat: "end",
    style: "lab",
    cost: { metal: 130, gold: 8500 },
    hp: 2400,
    size: [2, 2],
    blocksPlayer: true,
    blocksZombies: true,
    blocksCrawlers: true,
    unique: true,
    lab: true,
    powerUse: 2,
  },
  nuclear: {
    name: "Nuclear Generator",
    tier: 5,
    cat: "end",
    style: "generator",
    cost: { metal: 160, gold: 11000 },
    hp: 2800,
    size: [2, 2],
    blocksPlayer: true,
    blocksZombies: true,
    blocksCrawlers: true,
    power: 12,
    unique: true,
  },
};

export const BUILD_CATS = [
  { id: "basic", name: "Basic" },
  { id: "fort", name: "Fort" },
  { id: "military", name: "Military" },
  { id: "end", name: "Endgame" },
];

export function buildingsInCat(cat) {
  return Object.entries(BUILDINGS)
    .filter(([, def]) => def.cat === cat && !def.hidden)
    .map(([id, def]) => ({ id, ...def }));
}

export const TIER_PALETTE = {
  0: { main: 0xa56b3c, trim: 0x6b3e22, roof: 0x8a4d2c, metal: 0x8d6a45 },
  1: { main: 0x9aa0a6, trim: 0x5c6168, roof: 0x7a828a, metal: 0xb7b1a4 },
  2: { main: 0x8b9096, trim: 0x4c545b, roof: 0x6a7278, metal: 0xa8a297 },
  3: { main: 0x6e868e, trim: 0x24383e, roof: 0x4c646c, metal: 0x9eb0b4 },
  4: { main: 0x8d9698, trim: 0xc47a3a, roof: 0x3e484c, metal: 0xd5d2c8 },
  5: { main: 0xd5dbd6, trim: 0xff7a32, roof: 0x8e9a94, metal: 0xf2f0ea },
};

export function scaledCost(cost, multiplier) {
  const out = {};
  for (const [k, v] of Object.entries(cost || {})) {
    out[k] = Math.max(1, Math.ceil(v * multiplier));
  }
  return out;
}

export function repairCostOf(def, missing, mods) {
  const frac = Math.max(0.08, Math.min(1, missing));
  const mul = (mods && mods.repairCost) || 1;
  const out = {};
  const entries = Object.entries(def.cost || {});
  if (!entries.length) {
    out.wood = Math.max(1, Math.ceil(8 * frac));
    return out;
  }
  for (const [k, v] of entries) {
    const n = Math.ceil(v * frac * (k === "gold" ? 0.45 : 0.34) * mul);
    if (n > 0) out[k] = n;
  }
  return out;
}
